### ISSUE TITLE
Use the internal LED and Speaker

### ISSUE THREAD

**Issue by jongerenchaos** [openlumi/xiaomi-gateway-openwrt#1]
Very nice project, firmware without a cloud xiaomi server!

Is there also an option to use the internal speaker and led + sensors?

**Comment by devbis** [comment]
The instruction provides the fina system with stock kernel.
Kernel drivers and userspace devices are in place. So it depends on the userspace utilities. You can install MPD and use it as a music player. 
Also, zesp32 project allows using led, sound and illuminance sensor with mqtt broker.
