### ISSUE TITLE
Error flash JN5169

### ISSUE THREAD

**Issue by emwu88** [openlumi/xiaomi-gateway-openwrt#3]
Procedure:
wget https://github.com/openlumi/ZiGate/releases/download/snapshot-20201201/ZigbeeNodeControlBridge_JN5169_FULL_FUNC_DEVICE_31e_115200.bin -O /tmp/zigate.bin 
jnflash /tmp/zigate.bin
jntool erase_pdm

Issue:
root@OpenWrt:~ jnflash domoticz_zigate.bin
Flash domoticz_zigate.bin
JennicModuleProgrammer Version: 0.11 (r1234)
Logging Serial port opened at iInitialSpeed (= 38400) to /tmp/flasher.log
Setting baudrate for port 3 to 1000000
Detected Chip: Unknown
MAC Address:   00:15:8D:00:04:7D:A7:0F
Erasing = 0%
Writing = 100%
Logging Error in verification to /tmp/flasher.log
root@OpenWrt:~# cat /tmp/flasher.log
Tue Dec 22 20:02:56 2020 - 2447 : Serial port opened at iInitialSpeed (= 38400)
Tue Dec 22 20:03:02 2020 - 2447 : Error in verification

**Comment by devbis** [comment]
It is a normal behavior, the chip in the gateway is locked for reading so the verification fails. 
You can ignore that error.
