### ISSUE TITLE
zigbee2mqtt port 8080 colision

### ISSUE THREAD

**Issue by emwu88** [openlumi/xiaomi-gateway-openwrt#6]
Port 8080 conflict zigbee2mqtt and domoticz.
Change in https://raw.githubusercontent.com/openlumi/openwrt-node-packages/master/node-zigbee2mqtt/files/configuration.yaml to for example:
-------
frontend:
  port: 8081
-------

**Comment by devbis** [comment]
zigbee2mqtt port is changed to 8090 by default:

https://github.com/openlumi/xiaomi-gateway-openwrt/commit/554e48f70f7938e99bb6a9920749b4e45a5a7e68#diff-dee9721cdf344532f5a18c59afc1dd4482ceddbe33ee5c277d94b12f17a1eb8aR26
